name: learn-github-actions
on: [push]
jobs:
  test-run-small:
    runs-on: ibm-x86-64-small
    steps:
    - run: echo "this is using a small runner"
  test-run-medium

    runs-on: ibm-x86-64-medium
    steps:
    - run: echo "this is using a medium runner"